spring:
  jpa:
    show-sql: true

# LocalStack para desenvolvimento local
aws:
  s3:
    endpoint: http://localhost:4566
    access-key: test
    secret-key: test
    bucket: contrato-ia-docs
    region: us-east-1
  sqs:
    endpoint: http://localhost:4566
    document-generation-queue-url: http://sqs.us-east-1.localhost.localstack.cloud:4566/000000000000/contrato-ia-generation.fifo

logging:
  level:
    br.com.contratoai: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
